version: '3.8'

services:
  frontend:
    image: nginx-frontend
    build: 
      context: ./frontend
      args:
        - REACT_APP_SERVICES_HOST=/services/m
    ports:
      - "8084:8084"
    networks: 
      - frontend
      - backend
  
  backend:
    image: nginx-backend
    build:
      context: ./backend
    networks: 
      - backend
    environment:
      - REDIS_URL=redisd
    depends_on: 
      - redisd

  redisd:
    ports:
      - '6379:6379'
    image: redis
    networks:
      - backend

networks: 
  frontend:
  backend:
